## 异常处理


根据抛出错误的代码所属的任务队列可以分为：

- 同步错误
- 异步错误（非Promise）
- Promise错误

### try...catch异常处理

通过使用try...catch结构包裹代码，当try代码块发生错误时，catch能捕获到错误的信息，页面可以继续执行。

```javascript
try {
  console.log(error); // 运行时错误
} catch(e) {
  console.log('捕捉到了');
}
```

但是 try...catch 处理异常的能力非常有限，**只能捕获到运行时非异步错误，对于语法错误和异步错误都捕捉不到**
**注意**如果我们用 await 把 promise 处理成了同步就可以捕获的的到

```javascript
  try {
    res = await this.$kmcApi.MonitorTemplate.promqlToQueryConfig(params)
  } catch (e) {
      this.promqlError = true
      this.monitorDataLoading = false
       return []
  }
```


### error事件

可以在window.onerror事件中捕获异常，它的捕获异常能力优于try...catch，主要原因在于：

- window.onerror是全局捕获，而try...catch针对的是具体的代码块
- window.onerror可以**捕获同步错误以及异步错误**

error事件还需要注意的是

- window.onerror无法捕获网络异常的错误
- window.onerror只有在返回true的时候，异常才不会向上抛出，否则即使捕获到了异常，控制台还是会显示Uncaught Error


### unhandledrejection

try..catch和window.onerror都无法捕获在Promise中抛出的错误, unhandlerejection的优势就在这里



